### ISSUE TITLE
Better SEO

### ISSUE THREAD

**Issue by amenk** [shopwareLabs/shopware6-phpstorm-plugin#149]
https://www.google.com/search?q=phpstorm+shopware+plugin yields https://www.shopware.com/de/news/shopware-plugin-fuer-phpstorm/ which is featuring the old plugin that seems to not be updated anymore?

Maybe the blog post can also mention this new plugin :-)

**Comment by shyim** [comment]
I have contacted JetBrains, to update this page https://www.jetbrains.com/help/phpstorm/shopware-integration.html . 
I think I have to write an Blog Post for shopware.com 😅

**Comment by amenk** [comment]
JetBrains updated the page and they was some blog post recently, too.
