### ISSUE TITLE
Show block usages for twig files (like interfaces in php)

### ISSUE THREAD

**Issue by dominikmank** [shopwareLabs/shopware6-phpstorm-plugin#183]
It would be really nice if it were possible to have an icon, or some sort of option, on a twig block where other twig files either extend or rewrite it.
It would be nice if the file was shown as a suggestion.

So if i have a file

foo.html.twig
```.html.twig
{% block test_block %}
some stuff
{% endblock %}
```

and a foo2.html.twig
```.html.twig
{% sw_extends "foo.html.twig" %}

{% block test_block %}
other stuff
{{ parent() }}
{% endblock %}
```

it would be nice, if a user can jump to both files by an icon on the block, or via the context menu.

**Comment by shyim** [comment]
@Haehnchen this is part of the Symfony Plugin Paid tier right? I have that out of the box 🤔. I would not re-implement a paid feature of your plugin :)

**Comment by dominikmank** [comment]
yes, just bought the license :D it works with the symfony plugin.
