### ISSUE TITLE
Add json schema mapping for shopware-cli configurations

### ISSUE THREAD

**Issue by Schrank** [shopwareLabs/shopware6-phpstorm-plugin#199]
I just found a bug because I added the schema files to my phpstorm. It would be great if the module is shipping this functionality :-)

https://github.com/FriendsOfShopware/shopware-cli/blob/main/extension/shopware-extension-schema.json
https://github.com/FriendsOfShopware/shopware-cli/blob/main/shop/shopware-project-schema.json

**Comment by shyim** [comment]
I don't get what you want 🙈  🤔

**Comment by Schrank** [comment]
In the lower right corner one can choose a schema to validate the json file against:
<img width="505" alt="image" src="https://github.com/shopwareLabs/shopware6-phpstorm-plugin/assets/379680/48d13a56-aa3c-41ac-9383-bbf441095df6">


Currently the two schemas from shopware-cli are not part of the list, therefore I added it. The problem is, this is a [per-project setting](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004467239-Global-JSON-Schema-Mappings) and therefore it would be great to
1. Add the two schema files to the schema database by phpstorm
2. Automatically apply the correct schema to have auto-validation by phpstorm

**Comment by shyim** [comment]
![image](https://github.com/shopwareLabs/shopware6-phpstorm-plugin/assets/6224096/59fc5d3a-9e8a-4015-b08c-bb77a5b9c8d0)

try this and then it should just work. These schema are registered in the schemastore project and therefore should automaticaly configure in every IDE

**Comment by Schrank** [comment]
Ah, thanks!
