### ISSUE TITLE
Minor: Unnecessary edit prompt when trying to extend a vendor block

### ISSUE THREAD

**Issue by amenk** [shopwareLabs/shopware6-phpstorm-plugin#58]
1. Open for example vendor/shopware/storefront/Resources/views/storefront/page/product-detail/buy-widget.html.twig
2. Press alt-enter on page_product_detail_buy_form_inner -> Extend this block
3. Non-Project file protection kicks in - which seems not necessary, because I do not want to change the vendor file at all 
![Non-Project file protection](https://user-images.githubusercontent.com/1087128/169957972-20725a31-a2d4-4deb-976b-0c100c2da4c8.png)

v0.0.25

**Comment by shyim** [comment]
Did you choose the Extension of vendor 🤔

**Comment by amenk** [comment]
The block I try to overwrite is defined in vendor, the popup comes before even being able to chose the local target extension for the overwrite. So I think the answer is "no" ;-) Or am I getting it wrong?

**Comment by shyim** [comment]
I just asked for the Slack for help with the modal

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/170668544-377ca48f-9492-4aa2-bbef-de9422a00739.png)
ooopf 🙈

**Comment by amenk** [comment]
It's not high priority though :-)

**Comment by amenk** [comment]
One option might be to use an own hotkey. This is how Magicento does it... maybe that is easier, but has the drawback of not having everything in one place?
On the other hand, the Alt+Enter shortcut might kind of meant for modifying code at the current position?

**Comment by shyim** [comment]
That could be a solution yep 🤔 . Instead of an intention, just a action which can be find to hotkey or used using right click on that block 🤔

**Comment by shyim** [comment]
You can do right click on any block and then press extend this block. You can bind it also to a key in the key map settings
