### ISSUE TITLE
Extrend this block with Shopware 6.4.11.1 and a fresh theme-skeleton? 

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopwareLabs/shopware6-phpstorm-plugin#65]
I just used the "Extend this block" functionality in my shopware 6.4.11.1 instance and with a fresh theme-skeleton. I was very confused why my changes within the Theme didn't get used by shopware. 

I just found out that this function creates a folder within "ThemePluginRoot/Resources/views/" , but shopware recognizes templates only in "ThemePluginRoot/**src**/Resources/views/" directory.

The problem does not appear anymore, once the "views" directory exists inside the template.

**Comment by zaifastafa** [comment]
@shyim Yes this happened for me as well I think after a more recent update. It used to work fine before.
